// usersData.js
const usersData = [
  {
      id: 1,
      name: "Shankar Chakraborty",
      email: "shankar@gmail.com",
      mobile: "+919832670211",
      address: "Kolkata",
      purchasedNotes: [
          { id: 100, title: "React JS" },
          { id: 101, title: "SpringBoot" },
      ],
  },
  {
      id: 2,
      name: "Surya Ghosh",
      email: "surya@gmail.com",
      mobile: "+919832670212",
      address: "Mumbai",
      purchasedNotes: [
          { id: 102, title: "Java" },
          { id: 103, title: "C++" },
      ],
  },
  {
      id: 3,
      name: "John Doe",
      email: "john@gmail.com",
      mobile: "+919832670213",
      address: "Delhi",
      purchasedNotes: [
          { id: 104, title: "C" },
          { id: 105, title: "Rust" },
          { id: 106, title: "Go Lang" },
      ],
  },
  {
      id: 4,
      name: "Jane Smith",
      email: "jane@gmail.com",
      mobile: "+919832670214",
      address: "Bangalore",
      purchasedNotes: [
          { id: 107, title: "Python" },
          { id: 108, title: "Django" },
      ],
  },
  {
      id: 5,
      name: "Alice Johnson",
      email: "alice@gmail.com",
      mobile: "+919832670215",
      address: "Chennai",
      purchasedNotes: [
          { id: 109, title: "JavaScript" },
          { id: 110, title: "Node.js" },
      ],
  },
  {
      id: 6,
      name: "Bob Brown",
      email: "bob@gmail.com",
      mobile: "+919832670216",
      address: "Hyderabad",
      purchasedNotes: [
          { id: 111, title: "Angular" },
          { id: 112, title: "Vue.js" },
      ],
  },
  {
      id: 7,
      name: "Charlie Davis",
      email: "charlie@gmail.com",
      mobile: "+919832670217",
      address: "Pune",
      purchasedNotes: [
          { id: 113, title: "SQL" },
          { id: 114, title: "NoSQL" },
      ],
  },
  {
      id: 8,
      name: "David Evans",
      email: "david@gmail.com",
      mobile: "+919832670218",
      address: "Ahmedabad",
      purchasedNotes: [
          { id: 115, title: "PHP" },
          { id: 116, title: "Laravel" },
      ],
  },
  {
      id: 9,
      name: "Eve Foster",
      email: "eve@gmail.com",
      mobile: "+919832670219",
      address: "Surat",
      purchasedNotes: [
          { id: 117, title: "Ruby" },
          { id: 118, title: "Rails" },
      ],
  },
  {
      id: 10,
      name: "Frank Green",
      email: "frank@gmail.com",
      mobile: "+919832670220",
      address: "Jaipur",
      purchasedNotes: [
          { id: 119, title: "Kotlin" },
          { id: 120, title: "Android" },
      ],
  },
  {
      id: 11,
      name: "Grace Harris",
      email: "grace@gmail.com",
      mobile: "+919832670221",
      address: "Lucknow",
      purchasedNotes: [
          { id: 121, title: "Swift" },
          { id: 122, title: "iOS" },
      ],
  },
  {
      id: 12,
      name: "Henry Johnson",
      email: "henry@gmail.com",
      mobile: "+919832670222",
      address: "Kanpur",
      purchasedNotes: [
          { id: 123, title: "C#" },
          { id: 124, title: ".NET" },
      ],
  },
  {
      id: 13,
      name: "Ivy King",
      email: "ivy@gmail.com",
      mobile: "+919832670223",
      address: "Nagpur",
      purchasedNotes: [
          { id: 125, title: "Perl" },
          { id: 126, title: "Raku" },
      ],
  },
  {
      id: 14,
      name: "Jack Lee",
      email: "jack@gmail.com",
      mobile: "+919832670224",
      address: "Indore",
      purchasedNotes: [
          { id: 127, title: "Scala" },
          { id: 128, title: "Akka" },
      ],
  },
  {
      id: 15,
      name: "Kate Martin",
      email: "kate@gmail.com",
      mobile: "+919832670225",
      address: "Thane",
      purchasedNotes: [
          { id: 129, title: "Haskell" },
          { id: 130, title: "Elm" },
      ],
  },
  {
      id: 16,
      name: "Leo Nelson",
      email: "leo@gmail.com",
      mobile: "+919832670226",
      address: "Bhopal",
      purchasedNotes: [
          { id: 131, title: "Elixir" },
          { id: 132, title: "Phoenix" },
      ],
  },
  {
      id: 17,
      name: "Mia Owens",
      email: "mia@gmail.com",
      mobile: "+919832670227",
      address: "Visakhapatnam",
      purchasedNotes: [
          { id: 133, title: "F#" },
          { id: 134, title: "Fable" },
      ],
  },
  {
      id: 18,
      name: "Noah Perez",
      email: "noah@gmail.com",
      mobile: "+919832670228",
      address: "Patna",
      purchasedNotes: [
          { id: 135, title: "OCaml" },
          { id: 136, title: "ReasonML" },
      ],
  },
  {
      id: 19,
      name: "Olivia Quinn",
      email: "olivia@gmail.com",
      mobile: "+919832670229",
      address: "Vadodara",
      purchasedNotes: [
          { id: 137, title: "Erlang" },
          { id: 138, title: "LFE" },
      ],
  },
  {
      id: 20,
      name: "Paul Roberts",
      email: "paul@gmail.com",
      mobile: "+919832670230",
      address: "Ghaziabad",
      purchasedNotes: [
          { id: 139, title: "Scheme" },
          { id: 140, title: "Racket" },
      ],
  },
  {
      id: 21,
      name: "Quinn Smith",
      email: "quinn@gmail.com",
      mobile: "+919832670231",
      address: "Agra",
      purchasedNotes: [
          { id: 141, title: "Common Lisp" },
          { id: 142, title: "Clojure" },
      ],
  },
  {
      id: 22,
      name: "Ryan Taylor",
      email: "ryan@gmail.com",
      mobile: "+919832670232",
      address: "Nashik",
      purchasedNotes: [
          { id: 143, title: "Fortran" },
          { id: 144, title: "COBOL" },
      ],
  },
  {
      id: 23,
      name: "Sophia Underwood",
      email: "sophia@gmail.com",
      mobile: "+919832670233",
      address: "Faridabad",
      purchasedNotes: [
          { id: 145, title: "Pascal" },
          { id: 146, title: "Ada" },
      ],
  },
  {
      id: 24,
      name: "Thomas Vargas",
      email: "thomas@gmail.com",
      mobile: "+919832670234",
      address: "Meerut",
      purchasedNotes: [
          { id: 147, title: "VHDL" },
          { id: 148, title: "Verilog" },
      ],
  },
  {
      id: 25,
      name: "Uma Walker",
      email: "uma@gmail.com",
      mobile: "+919832670235",
      address: "Rajkot",
      purchasedNotes: [
          { id: 149, title: "Assembly" },
          { id: 150, title: "Machine Code" },
      ],
  },
  {
      id: 26,
      name: "Victor Xander",
      email: "victor@gmail.com",
      mobile: "+919832670236",
      address: "Jabalpur",
      purchasedNotes: [
          { id: 151, title: "Prolog" },
          { id: 152, title: "Mercury" },
      ],
  },
  {
      id: 27,
      name: "Wendy Young",
      email: "wendy@gmail.com",
      mobile: "+919832670237",
      address: "Gwalior",
      purchasedNotes: [
          { id: 153, title: "D" },
          { id: 154, title: "Nim" },
      ],
  },
  {
      id: 28,
      name: "Xander Zane",
      email: "xander@gmail.com",
      mobile: "+919832670238",
      address: "Vijayawada",
      purchasedNotes: [
          { id: 155, title: "Crystal" },
          { id: 156, title: "Amber" },
      ],
  },
  {
      id: 29,
      name: "Yara Anderson",
      email: "yara@gmail.com",
      mobile: "+919832670239",
      address: "Madurai",
      purchasedNotes: [
          { id: 157, title: "R" },
          { id: 158, title: "SAS" },
      ],
  },
  {
      id: 30,
      name: "Zane Brown",
      email: "zane@gmail.com",
      mobile: "+919832670240",
      address: "Amritsar",
      purchasedNotes: [
          { id: 159, title: "Matlab" },
          { id: 160, title: "Octave" },
      ],
  },
  {
      id: 31,
      name: "Alan Carter",
      email: "alan@gmail.com",
      mobile: "+919832670241",
      address: "Allahabad",
      purchasedNotes: [
          { id: 161, title: "Lisp" },
          { id: 162, title: "Racket" },
      ],
  },
  {
      id: 32,
      name: "Betty Davis",
      email: "betty@gmail.com",
      mobile: "+919832670242",
      address: "Ranchi",
      purchasedNotes: [
          { id: 163, title: "Scratch" },
          { id: 164, title: "Blockly" },
      ],
  },
  {
      id: 33,
      name: "Charles Evans",
      email: "charles@gmail.com",
      mobile: "+919832670243",
      address: "Howrah",
      purchasedNotes: [
          { id: 165, title: "Logo" },
          { id: 166, title: "Turtle" },
      ],
  },
  {
      id: 34,
      name: "Diana Foster",
      email: "diana@gmail.com",
      mobile: "+919832670244",
      address: "Coimbatore",
      purchasedNotes: [
          { id: 167, title: "Smalltalk" },
          { id: 168, title: "Squeak" },
      ],
  },
  {
      id: 35,
      name: "Edward Green",
      email: "edward@gmail.com",
      mobile: "+919832670245",
      address: "Jodhpur",
      purchasedNotes: [
          { id: 169, title: "Forth" },
          { id: 170, title: "Factor" },
      ],
  },
  {
      id: 36,
      name: "Fiona Harris",
      email: "fiona@gmail.com",
      mobile: "+919832670246",
      address: "Guwahati",
      purchasedNotes: [
          { id: 171, title: "APL" },
          { id: 172, title: "J" },
      ],
  },
  {
      id: 37,
      name: "George Irwin",
      email: "george@gmail.com",
      mobile: "+919832670247",
      address: "Chandigarh",
      purchasedNotes: [
          { id: 173, title: "PostScript" },
          { id: 174, title: "PDF" },
      ],
  },
  {
      id: 38,
      name: "Hannah Jones",
      email: "hannah@gmail.com",
      mobile: "+919832670248",
      address: "Thiruvananthapuram",
      purchasedNotes: [
          { id: 175, title: "Dart" },
          { id: 176, title: "Flutter" },
      ],
  },
  {
      id: 39,
      name: "Isaac King",
      email: "isaac@gmail.com",
      mobile: "+919832670249",
      address: "Mysore",
      purchasedNotes: [
          { id: 177, title: "ActionScript" },
          { id: 178, title: "Flex" },
      ],
  },
  {
      id: 40,
      name: "Julia Lee",
      email: "julia@gmail.com",
      mobile: "+919832670250",
      address: "Hubli",
      purchasedNotes: [
          { id: 179, title: "ColdFusion" },
          { id: 180, title: "MXML" },
      ],
  },
  {
      id: 41,
      name: "Kevin Miller",
      email: "kevin@gmail.com",
      mobile: "+919832670251",
      address: "Salem",
      purchasedNotes: [
          { id: 181, title: "Modula-2" },
          { id: 182, title: "Oberon" },
      ],
  },
  {
      id: 42,
      name: "Laura Nelson",
      email: "laura@gmail.com",
      mobile: "+919832670252",
      address: "Bhavnagar",
      purchasedNotes: [
          { id: 183, title: "Icon" },
          { id: 184, title: "Unicon" },
      ],
  },
  {
      id: 43,
      name: "Mason Oliver",
      email: "mason@gmail.com",
      mobile: "+919832670253",
      address: "Warangal",
      purchasedNotes: [
          { id: 185, title: "REBOL" },
          { id: 186, title: "Red" },
      ],
  },
  {
      id: 44,
      name: "Nina Patel",
      email: "nina@gmail.com",
      mobile: "+919832670254",
      address: "Siliguri",
      purchasedNotes: [
          { id: 187, title: "Awk" },
          { id: 188, title: "Sed" },
      ],
  },
  {
      id: 45,
      name: "Oscar Quinn",
      email: "oscar@gmail.com",
      mobile: "+919832670255",
      address: "Durgapur",
      purchasedNotes: [
          { id: 189, title: "Rexx" },
          { id: 190, title: "NetRexx" },
      ],
  },
  {
      id: 46,
      name: "Penny Roberts",
      email: "penny@gmail.com",
      mobile: "+919832670256",
      address: "Bhubaneswar",
      purchasedNotes: [
          { id: 191, title: "JCL" },
          { id: 192, title: "z/OS" },
      ],
  },
  {
      id: 47,
      name: "Quentin Smith",
      email: "quentin@gmail.com",
      mobile: "+919832670257",
      address: "Mangalore",
      purchasedNotes: [
          { id: 193, title: "Euphoria" },
          { id: 194, title: "Phix" },
      ],
  },
  {
      id: 48,
      name: "Rachel Taylor",
      email: "rachel@gmail.com",
      mobile: "+919832670258",
      address: "Kolhapur",
      purchasedNotes: [
          { id: 195, title: "Fantom" },
          { id: 196, title: "Sky" },
      ],
  },
  {
      id: 49,
      name: "Sam Underwood",
      email: "sam@gmail.com",
      mobile: "+919832670259",
      address: "Shimla",
      purchasedNotes: [
          { id: 197, title: "Io" },
          { id: 198, title: "Lua" },
      ],
  },
  {
      id: 50,
      name: "Tina Vargas",
      email: "tina@gmail.com",
      mobile: "+919832670260",
      address: "Amravati",
      purchasedNotes: [
          { id: 199, title: "Ring" },
          { id: 200, title: "Pico" },
      ],
  }
];

export default usersData;